// ClientApp/reactclient/src/routes/components/paginationlayout.jsx
import { Link } from 'react-router-dom';
import PropTypes from 'prop-types';
import { useEffect } from 'react';
import { useState } from 'react';

function PaginationLayout({url, totalPages}) {
    const [page, setPage] = useState(1);
    const [orderBy, setOrderBy] = useState('-discount');

    useEffect(() => {
        const urlParams = new URLSearchParams(url);
        setPage(urlParams.get('page') || 1);
        setOrderBy(urlParams.get('orderBy') || '-discount');
    }, [url, totalPages]);

    const scrollTop = () => {
        window.scrollTo({ top: 0, behavior: 'smooth' });
    }

    return (
    <div className="row">
        <div className="col-12">
            <div className="d-flex justify-content-center">
                {page > 1 && (
                <Link
                    className="btn btn-outline-primary mx-2 bottom-btn"
                    to={`${url ? `/${url}` : ''}?page=${parseInt(page) - 1}&orderBy=${orderBy}`}  
                    onClick={scrollTop}              >
                    Previous
                </Link>
                )}
                {page < totalPages && (
                <Link
                    className="btn btn-outline-primary mx-2 bottom-btn"
                    to={`${url ? `/${url}` : ''}?page=${parseInt(page) + 1}&orderBy=${orderBy}`}      
                    onClick={scrollTop}          >
                    Next
                </Link>
                )}
            </div>
        </div>
    </div>
    )   
}

PaginationLayout.propTypes = {
    url: PropTypes.string,
    totalPages: PropTypes.number.isRequired,
};

export default PaginationLayout;

// ClientApp/suppsclient/src/components/PaginationLayout.vue
<!-- <template>
    <div class="row">
      <div class="col-12">
        <div class="d-flex justify-content-center">
            <router-link :to="{ path: url, query: { page: previouspage, orderby: orderby } }" class="btn btn-outline-primary mx-2 bottom-btn" v-if="page > 1" @click="scrolltop">Previous</router-link>
            <router-link :to="{ path: url, query: { page: nextpage, orderby: orderby } }" class="btn btn-outline-primary mx-2 bottom-btn" v-if="page < totalPages" @click="scrolltop">Next</router-link>
        </div>
      </div>
    </div>
</template>

<script>
export default {
    name: 'PaginationLayout',
    props:
    {
        url: {
            type: String,
            required: true,
        },
        totalPages: {
            type: Number,
            required: true,
        },
    },
    data() {
        return {
            page: this.$route.query.page || 1,
            orderby: this.$route.query.orderby || '-discount',
        };
    },
    computed: {
        nextpage() {
            const page = parseInt(this.page);
            return page + 1;
        },
        previouspage() {
            const page = parseInt(this.page);
            return page - 1;
        },
    },
    watch: {
        $route(to) {
            this.page = to.query.page || 1;
            this.brand = to.query.brand || '';
            this.orderby = to.query.orderby || '-discount';
        }
    },
    methods: {
        scrolltop() {
            window.scrollTo(0, 0);
        }
    }
}
</script> -->

<template>
    <div class="row">
        <div class="col-12">
            <div class="d-flex justify-content-center">
                <router-link
                    :to="{ path: url, query: { page: previouspage, orderby: orderby, [pageType]: searchTerm } }"
                    class="btn btn-outline-primary mx-2 bottom-btn"
                    v-if="page > 1"
                    @click="scrolltop"
                >
                    Previous
                </router-link>
                <router-link
                    :to="{ path: url, query: { page: nextpage, orderby: orderby, [pageType]: searchTerm } }"
                    class="btn btn-outline-primary mx-2 bottom-btn"
                    v-if="page < totalPages"
                    @click="scrolltop"
                >
                    Next
                </router-link>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: "PaginationLayout",
    props: {
        url: {
            type: String,
            required: true,
        },
        totalPages: {
            type: Number,
            required: true,
        },
        pageType: {
            type: String,
            required: false,
            default: "",
        },
    },
    data() {
        return {
            page: this.$route.query.page || 1,
            orderby: this.$route.query.orderby || "-discount",
            searchTerm: this.$route.query[this.pageType] || "",
        };
    },
    computed: {
        nextpage() {
            const page = parseInt(this.page);
            return page + 1;
        },
        previouspage() {
            const page = parseInt(this.page);
            return page - 1;
        },
    },
    watch: {
        $route(to) {
            this.page = to.query.page || 1;
            this.orderby = to.query.orderby || "-discount";
            this.searchTerm = to.query[this.pageType] || "";
        },
    },
    methods: {
        scrolltop() {
            window.scrollTo(0, 0);
        },
    },
};
</script>
