// ClientApp/reactclient/src/routes/components/productlayout.jsx
import React from 'react';
import PropTypes from 'prop-types';
import { Link } from 'react-router-dom';

function ProductLayout({product}) {
    if(!product) return (<div>Loading...</div>);
    return (
        <div className="border rounded p-3 h-100">
            {/* <ProductImage :image="product.supplement.image" :url="product.url"/> */}
            <div className="product-name h-auto">
                <h5>{product.supplement.name}</h5>
                <div className="row h-auto">
                    <div className="col-3">
                        <div className="product-price">
                            <p> 
                                <span className="text-danger"><del>{product.supplement.originalPrice}</del></span>
                                $ {product.supplement.discountPrice}
                            </p>
                        </div>
                    </div>
                    <div className="col-9">
                        <div className="product-brand text-end">
                            {product.brand &&
                            <Link to={`/brand?brand=${product.brand.brandUrl}`} className="text-black">
                                <p className="mb-0">{product.brand.brandName}</p>
                            </Link>
                            }
                        </div>
                    </div>
                </div>
                <div className="row">
                    <div className="col-3">
                        <p>${product.supplement.discount}🔻</p>
                    </div>
                    <div className="col-9 text-end">
                        <a href="/" className="text-black">
                            <p>{product.supplement.advertiser}</p>
                        </a>
                    </div>
                </div>
                <div className="row">
                    <div className="text-center">
                        <a href={product.supplement.url} className="btn btn-primary w-75" target="_blank" rel="noopener noreferrer">View Product</a>
                    </div>
                </div>
            </div>
        </div>
    );
}

ProductLayout.propTypes = {
    product: PropTypes.shape({
        supplement: PropTypes.shape({
            name: PropTypes.string,
            originalPrice: PropTypes.number,
            discountPrice: PropTypes.number,
            discount: PropTypes.number,
            advertiser: PropTypes.string,
            url: PropTypes.string,
        }),
        brand: PropTypes.shape({
            brandUrl: PropTypes.string,
            brandName: PropTypes.string,
        }),
    }).isRequired,
};

export default ProductLayout;

// ClientApp/suppsclient/src/components/ProductLayout.vue
<script>
import ProductImage from '../components/ProductImage.vue';

export default{
    name: 'ProductLayout',
    components: {
        ProductImage
    },
    props: {
        product: {
            type: Object,
            required: true,
        },
    },
}
</script>

<template>
    
    <div class="border rounded p-3 h-100">
      <!-- {{ product }} -->
          <ProductImage :image="product.supplement.image" :url="product.url"/>
          <div class="product-name h-auto">
            <h5>{{product.supplement.name}}</h5>
            <div class="row h-auto">
              <div class="col-3">
                <div class="product-price">
                  <p> 
                    <span class="text-danger"><del>${{ product.supplement.originalPrice }}</del></span>
                    ${{ product.supplement.discountPrice }}
                  </p>
                </div>
              </div>
              <div class="col-9">
                <div class="product-brand text-end" v-if="product.brand">
                  <router-link :to="`/brand?brand=`+product.brand.brandUrl" class="text-black">
                    <p class="mb-0" >{{ product.brand.brandName }}</p>
                  </router-link>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-3">
                <p>${{product.supplement.discount}}🔻</p>
              </div>
              <div class="col-9 text-end" v-if="product.advertiser">
                <a href="/" class="text-black">
                  <p>{{ product.supplement.advertiser }}</p>
                </a>
              </div>
            </div>
            <div class="row">
              <div class="text-center">
                <a :href="product.supplement.url" class="btn btn-primary w-75" target="_blank">View Product</a>
              </div>
            </div>
          </div>
        </div>

</template>
