// ClientApp/suppsclient/src/components/SelectDropdown.vue
<template>
  <div class="col-4 col-lg-2">
    <select name="orderby" class="form-select" v-model="selectedValue">
      <option value="-discount">Discount</option>
      <option value="discount_price">Lowest Price</option>
      <option value="-discount_price">Highest Price</option>
    </select>
  </div>
</template>
  
<script>
export default {
  name: "SelectDropdown",
  computed: {
    selectedValue: {
      get() {
        return this.value; // Set the initial value of selectedValue
      },
      set(newValue) {
        this.$emit("input", newValue);
      },
    },
  },
};
</script>

// ClientApp/reactclient/src/routes/components/selectdropdown.jsx
import React from 'react';
import { useNavigate } from 'react-router-dom';

export default function SelectDropdown() {
    const navigate = useNavigate();

    const handleChange = (event) => {
        const orderBy = event.target.value;
        navigate(`?orderby=${orderBy}`);
    };

    return (
        <div className="col-4 col-lg-2">
            <select name="orderby" className="form-select" onChange={handleChange}>
                <option value="-discount">Discount</option>
                <option value="-discount_price">Lowest Price</option>
                <option value="discount_price">Highest Price</option>
            </select>
        </div> 
    );
}
